import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { LandingHeader } from "../components/header/LandingHeader";
import { navItems } from "../easyEdit/NavItems";

// ============================================
// FONT CONFIGURATION - Update these to change fonts across the entire site
// ============================================
// Available Google Fonts: https://fonts.google.com/
// To change fonts, import a different font here and update the variable names
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// ============================================

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-white">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white`}
      >
        <LandingHeader navItems={navItems} source="layout" />
        <div className="pt-14 bg-white min-h-screen">{children}</div>
      </body>
    </html>
  );
}
